MODEL:
  TYPE: generalized_rcnn
  SUBTYPE: 3
  USE_OVLP_FILTER: True
  USE_FREQ_BIAS: True
  NO_FC7_RELU: True
  USE_SPATIAL_FEAT: False
  ADD_SO_SCORES: True
  ADD_SCORES_ALL: True
  USE_BG: True
  CONV_BODY: VGG16.VGG16_conv_body
  USE_NODE_CONTRASTIVE_LOSS: True
  NODE_CONTRASTIVE_MARGIN: 0.2
  USE_NODE_CONTRASTIVE_SO_AWARE_LOSS: True
  NODE_CONTRASTIVE_SO_AWARE_MARGIN: 0.2
  NODE_CONTRASTIVE_SO_AWARE_WEIGHT: 0.5
  USE_NODE_CONTRASTIVE_P_AWARE_LOSS: True
  NODE_CONTRASTIVE_P_AWARE_MARGIN: 0.2
  NODE_CONTRASTIVE_P_AWARE_WEIGHT: 0.1
  NODE_SAMPLE_SIZE: 128
  FASTER_RCNN: True
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 62723  # 62723 images
  STEPS: [0, 41815, 55754]
VGG16:
  VG_PRETRAINED_WEIGHTS: 'detection_models/vg/VGG16/model_step479999.pth'
  VG_PRD_PRETRAINED_WEIGHTS: 'detection_models/vg/VGG16/model_step479999.pth'
FAST_RCNN:
  ROI_BOX_HEAD: VGG16.VGG16_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
RPN:
  SIZES: (32, 64, 128, 256, 512)
TRAIN:
  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
TEST:
  FORCE_JSON_DATASET_EVAL: True
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
