MODEL:
  TYPE: generalized_rcnn
  SUBTYPE: 3
  USE_OVLP_FILTER: True
  USE_FREQ_BIAS: True
  NO_FC7_RELU: True
  USE_SPATIAL_FEAT: False #True
  ADD_SO_SCORES: False #True
  ADD_SCORES_ALL: True
  MULTI_RELATION: True #False
  USE_BG: True
  CONV_BODY: ResNet.ResNet101_conv5_body
  REL_CONV_BODY: ResNet.ResNet50_conv5_body_dilation2
  USE_NODE_CONTRASTIVE_LOSS: False
  NODE_CONTRASTIVE_MARGIN: 0.2
  USE_NODE_CONTRASTIVE_SO_AWARE_LOSS: False
  NODE_CONTRASTIVE_SO_AWARE_MARGIN: 0.2
  NODE_CONTRASTIVE_SO_AWARE_WEIGHT: 0.5
  USE_NODE_CONTRASTIVE_P_AWARE_LOSS: False
  NODE_CONTRASTIVE_P_AWARE_MARGIN: 0.2
  NODE_CONTRASTIVE_P_AWARE_WEIGHT: 0.1
  NODE_SAMPLE_SIZE: 128
  FASTER_RCNN: True
  UNFREEZE_DET: False
  USE_REL_COMPETITE_LOSS_WEIGHT: -1.0
  USE_TRIPLET_PENALTY_LOSS_WEIGHT: -1.0
  USE_OBJ_LOSS_WEIGHT: 0.05
  ALL_OBJ_WITH_REL_WEIGHT: -1.0 #1.0
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 177330
  STEPS: [0, 118220, 157626] 
RESNETS:
  VG_PRETRAINED_WEIGHTS: 'detection_models/ag/res101/COCO_pretrained/res101_ag_4it.pth'
  VG_PRD_PRETRAINED_WEIGHTS: 'detection_models/ag/i3d/i3d_nl_dot_product_r50_32x2x1_100e_kinetics400_rgb_20200814-7c30d5bb.pth'
  PRD_2D_PRETRAINED_WEIGHTS: 'detection_models/ag/res50/COCO_pretrained/res50_1it.pth'
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  RES5_DILATION: 2
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
RPN:
  SIZES: (32, 64, 128, 256, 512)
  FREEZE_RPN: True
TRAIN:
  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  EVA_BATCHNORM: True # False
  SNAPSHOT_FREQ: 10
TEST:
  FORCE_JSON_DATASET_EVAL: True
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
HALF_NUMBER_OF_FRAMES: 8
FRAMES_INTERVAL: 4
ENABLE_FRAME_SAMPLE: False
ENABLE_FRAME_PRE_PROCESSING: False
FREEZE_PART_I3D: True
I3D_DC5: True